### ISSUE TITLE
Comment checker will flag W9401 and W9402 on a string that contains a '#'

### ISSUE THREAD

**Issue by jwaterhouse** [twisted/twistedchecker#135] opened 2017-10-15 11:52 UTC
Bit of an edge case, but if I declare a python string containing a '#' character it gets picked up and checked as a comment.

See the following diff for an example that triggers the problem (a '#' symbol in the anchor portion of a URL) and workaround for the problem (declare the string inside triple quotes ["""] on a new line).

https://github.com/twisted/twisted/pull/914/commits/b7447a14ab29874ff058ad44323e25c955e04bc1

**Comment by adiroiban** [comment] 2017-10-15 19:44
Thanks for the report. This is a duplicate of #110

**Closed by adiroiban** 2017-10-15 19:44 UTC
