### ISSUE TITLE
twistedchecker complains about a missing test header 

### ISSUE THREAD

**Issue by exarkun-insecure** [twisted/twistedchecker#49] opened 2014-04-16 21:01 UTC
twistedchecker complains about a missing test header in a __init__.py file that only has a docstring. for reference, please see http://twistedmatrix.com/trac/ticket/6482 and https://twistedmatrix.com/trac/ticket/6482#comment:3

------------------------------------
Imported from Launchpad using lp2gh.

 * date created: 2013-04-27T18:49:35Z
 * owner: mq
 * the launchpad url was https://bugs.launchpad.net/bugs/1173713

**Comment by adiroiban** [comment] 2015-02-10 11:48
I am closing it  as is this is not a bug. packages should also have a reference to tests.

In case you think this is still a bug, please raise the issue over the twisted mailing list so that it gets the attention of all developers.

**Closed by adiroiban** 2015-02-10 11:48 UTC
Labels: New, Undecided
